# Wrangler configuration for Digital Rights Collective
name = "digital-rights-collective"
compatibility_date = "2023-10-30"

[site]
bucket = "./dist"

[build]
command = "npm run build"
output_directory = "dist"

# Environment variables
[env.production]
# Add any production-specific environment variables here if needed
# MY_VAR = "production_value"

[env.preview]
# Add any preview-specific environment variables here if needed
# MY_VAR = "preview_value"